/**
 * Signal.js — AI-generated market intelligence signals
 *
 * Signals are global (not per-user). Generated by Gemini and cached
 * for 24 hours in MongoDB. Frontend polls GET /api/signals which
 * returns cached signals if valid, or generates fresh ones if expired.
 */

import mongoose from "mongoose";

const signalSchema = new mongoose.Schema({
  type: {
    type: String,
    enum: ["talent", "code", "web", "funding", "compliance", "news"],
    required: true,
    index: true,
  },
  companyName:     { type: String, required: true },
  headline:        { type: String, required: true },     // short, punchy, max 8 words
  description:     { type: String, required: true },     // 2 sentences with specific metrics
  metricLabel:     { type: String },                     // e.g. "Open Roles", "Commit Spike"
  metricValue:     { type: String },                     // e.g. "+12 Roles", "450% increase"
  confidenceScore: { type: Number, min: 0, max: 100, default: 80 },
  category:        { type: String },                     // uppercase display label e.g. "TALENT"
  timeAgo:         { type: String, default: "JUST NOW" },// display string
  isGlobal:        { type: Boolean, default: true },
  generatedAt:     { type: Date, default: Date.now },
  expiresAt:       { type: Date, required: true },
});

// TTL index — MongoDB auto-deletes expired signals after the expiry date
signalSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });

export default mongoose.model("Signal", signalSchema);
